-- Entirely synthetic example. Use on CSVs generated by python analysis.py.
-- Expected vs simulated observed tiers
SELECT expected_tier, observed_tier,
       COUNT(*) AS accounts,
       SUM(mismatch) AS injected_exceptions
FROM synthetic_reconciliation
GROUP BY expected_tier, observed_tier
ORDER BY accounts DESC;

-- Consistency check. Expect 0 rows.
SELECT account_id FROM synthetic_reconciliation
WHERE mismatch <> CASE WHEN expected_tier <> observed_tier THEN 1 ELSE 0 END;
